language: cpp

branches:
  only:
    - main

compiler:
    - gcc

services:
    - docker

addons:
  apt:
    packages:
      - doxygen
      - graphviz

before_script:
    - ./ci/build/docs.sh

jobs:
  include:
    - stage: "Build"
      name: "Sample project"
      script: ./ci/build/sample.sh
    - stage: "Test"
      name: "Unit"
      script: ./ci/test/unit.sh
    - stage: "Test"
      name: "Integration"
      script: ./ci/test/integration.sh

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: main
