language: cpp

branches:
  only:
    - main

compiler:
    - gcc

services:
    - docker

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

jobs:
  include:
    - stage: "Build"
      name: "Sample project"
      script: ./ci/build/sample.sh
    - stage: "Build"
      name: "Unit tests"
      script: ./ci/build/unit.sh
    - stage: "Build"
      name: "Integration tests"
      script: ./ci/build/integration.sh
    - stage: "Build"
      name: "Documentation"
      script: ./ci/build/docs.sh
    - stage: "Test"
      name: "Unit tests"
      script: ./ci/test/unit.sh
    - stage: "Test"
      name: "Integration tests"
      script: ./ci/test/integration.sh

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: main
