language: cpp

branches:
  only:
    - main

compiler:
    - gcc

services:
    - docker

addons:
  apt:
    packages:
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz

before_script:
    - doxygen Doxyfile
    - docker build -t cpp-syslog-client -f test_pkg/Dockerfile .

jobs:
  include:
    - stage: "Unit tests"
      name: "Unit tests"
      script: ./ci/test.sh
    - stage: "Integration tests"
      name: "Integration tests"
      script: docker run cpp-syslog-client

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: html
  github_token: $GH_REPO_TOKEN
  on:
    branch: main
